language: node_js
node_js:
  - 0.8
before_install:
  - git submodule update --init --recursive
before_script:
  - npm install
  - ./node_modules/.bin/jshint .
  - node makefile.js build
  - node makefile.js server &
  - sleep 5
script: phantomjs tests/resources/phantom-run-qunit.js http://localhost:4000/tests/index.html